Repository trussworks/react-uswds, pull requests merged in 2020-04, with the labels that each got.

#48 resolve 2/3 security advisories
  package.json
  yarn.lock
Labels: dependencies, security

#101 Additional CSS utility classes
  .storybook/config.ts
  .stylelintrc
  CHANGELOG.md
  package.json
  src/index.ts
  src/stories/swatches.stories.tsx
  src/stories/type.stories.tsx
  src/styles/_backgrounds.scss
  src/styles/_type.scss
  src/styles/index.scss
  src/uswdsResources.scss
  yarn.lock
Labels: enhancement

#125 Release 1.2.0
  .circleci/config.yml
  .github/workflows/auto-approve.yml
  .github/workflows/deploy-storybook.yml
  .storybook/config.ts
  .stylelintrc
  CHANGELOG.md
  CODEOWNERS
  README.md
  dangerfile.ts
  package.json
  src/components/Alert/Alert.stories.tsx
  src/components/Alert/Alert.test.tsx
  src/components/Alert/Alert.tsx
  src/components/forms/Form/Form.stories.tsx
  src/index.ts
  src/stories/swatches.stories.tsx
  src/stories/type.stories.tsx
  src/styles/_backgrounds.scss
  src/styles/_type.scss
  src/styles/index.scss
  src/uswdsResources.scss
  yarn.lock
Labels: release
