Repository trussworks/react-uswds, pull requests merged in 2020-08, with the labels that each got.

#374 ci(danger): fix spurious warnings on changes to example code
  dangerfile.ts
Labels: type: bug, type: development

#364 docs: Point users to react-fontawesome for icons
  README.md
  example/package.json
  example/src/App.tsx
  example/src/pages/Icons.tsx
  example/src/routes.js
  example/yarn.lock
Labels: type: documentation

#382 feat(ButtonGroup): Add new component ButtonGroup
  src/components/ButtonGroup/ButtonGroup.stories.tsx
  src/components/ButtonGroup/ButtonGroup.test.tsx
  src/components/ButtonGroup/ButtonGroup.tsx
  src/index.ts
Labels: type: feature

#383 feat(CharacterCount): Add new component CharacterCount
  src/components/forms/CharacterCount/CharacterCount.stories.tsx
  src/components/forms/CharacterCount/CharacterCount.test.tsx
  src/components/forms/CharacterCount/CharacterCount.tsx
  src/components/forms/TextInput/TextInput.tsx
  src/components/forms/Textarea/Textarea.tsx
  src/index.ts
Labels: type: feature

#387 chore(release): 1.9.0
  CHANGELOG.md
  package.json
  yarn.lock
Labels: type: release

#398 ci(dependabot): Adjust config to merge earlier in day, ignore react dependencies
  .github/dependabot.yml
Labels: type: dependencies

#415 fix(search): Add a placeholder to Search TextInput #403
  src/components/Search/Search.stories.tsx
  src/components/Search/Search.test.tsx
  src/components/Search/Search.tsx
Labels: type: bug

#416 chore(release): 1.9.1
  CHANGELOG.md
  package.json
Labels: type: release

#418 docs(storybook): Upgrade to 6.0.12
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  src/index.ts
  yarn.lock
Labels: type: documentation
