Repository trussworks/react-uswds, pull requests merged in 2020-09, with the labels that each got.

#449 chore: Update bl dependency to resolve security advisory
  package.json
  yarn.lock
Labels: high priority, type: dependencies, type: security

#452 chore(release): 1.9.2
  CHANGELOG.md
  package.json
Labels: type: release

#453 fix: Happo automation should skip dependabot PRs
  .circleci/config.yml
  .github/dependabot.yml
Labels: type: bug, type: dependencies

#476 fix: update example app deps to fix security issue
  example/yarn.lock
Labels: type: security

#455 docs: Add Code of Conduct
  CODE_OF_CONDUCT.md
  README.md
  docs/contributing.md
Labels: type: documentation
