Repository trussworks/react-uswds, pull requests merged in 2020-06, with the labels that each got.

#215 fix: expand required node version range to 10.x - 12.x
  package.json
Labels: high priority, type: bug

#227 chore(release): 1.5.0
  CHANGELOG.md
  package.json
Labels: type: release

#205 feat: add card component #168
  src/components/card/Card.stories.tsx
  src/components/card/Card/Card.test.tsx
  src/components/card/Card/Card.tsx
  src/components/card/CardBody/CardBody.test.tsx
  src/components/card/CardBody/CardBody.tsx
  src/components/card/CardFooter/CardFooter.test.tsx
  src/components/card/CardFooter/CardFooter.tsx
  src/components/card/CardGroup/CardGroup.test.tsx
  src/components/card/CardGroup/CardGroup.tsx
  src/components/card/CardHeader/CardHeader.test.tsx
  src/components/card/CardHeader/CardHeader.tsx
  src/components/card/CardMedia/CardMedia.test.tsx
  src/components/card/CardMedia/CardMedia.tsx
  src/components/grid/Grid/Grid.test.tsx
  src/components/grid/Grid/Grid.tsx
Labels: status: wip

#237 docs(example-app): Example app UI #202
  docs/contributing.md
  example/README.md
  example/package.json
  example/src/App.css
  example/src/App.tsx
  example/src/pages/Example.tsx
  example/src/pages/Home.tsx
  example/yarn.lock
  package.json
Labels: type: example
