Repository trussworks/react-uswds, pull requests merged in 2020-07, with the labels that each got.

#320 chore(release): 1.7.0
  CHANGELOG.md
  package.json
Labels: type: release

#348 chore(release): 1.8.0
  CHANGELOG.md
  package.json
Labels: type: release

#362 fix(Button): Deprecate icon, size small properties
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.test.tsx
  src/components/Button/Button.tsx
Labels: type: bug

#351 feat(Validation): Add new Validation components
  example/package.json
  example/src/App.tsx
  example/src/pages/Example.tsx
  example/src/pages/Forms.tsx
  example/src/pages/Home.tsx
  example/src/routes.js
  example/yarn.lock
  src/components/Alert/Alert.test.tsx
  src/components/Alert/Alert.tsx
  src/components/forms/Validation/Validation.stories.tsx
  src/components/forms/Validation/ValidationChecklist.test.tsx
  src/components/forms/Validation/ValidationChecklist.tsx
  src/components/forms/Validation/ValidationItem.test.tsx
  src/components/forms/Validation/ValidationItem.tsx
  src/index.ts
Labels: type: feature

#365 ci: Dependabot should update /example dependencies
  .github/dependabot.yml
Labels: type: bug, type: dependencies
