Repository trussworks/react-uswds, pull requests merged in 2020-05, with the labels that each got.

#120 add yarn audit guidance (fixes #99)
  CHANGELOG.md
  README.md
  dangerfile.ts
  docs/contributing.md
Labels: devtools, documentation

#123 feat: add Grid components #86
  CHANGELOG.md
  dangerfile.ts
  package.json
  src/components/grid/Grid.stories.tsx
  src/components/grid/Grid/Grid.test.tsx
  src/components/grid/Grid/Grid.tsx
  src/components/grid/GridContainer/GridContainer.test.tsx
  src/components/grid/GridContainer/GridContainer.tsx
  src/components/grid/types.ts
  src/index.ts
Labels: enhancement, new component

#157 chore: upgrade sb-deployer (patch upgrade 2.8.5 => 2.8.6)
  package.json
  yarn.lock
Labels: dependencies, security

#211 chore(release): Release 1.4.0
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/semantic_pr.yml
  CHANGELOG.md
  README.md
  commitlint.config.js
  docs/contributing.md
  docs/for_trussels.md
  package.json
  src/components/Footer/Address/Address.stories.tsx
  src/components/Footer/Address/Address.test.tsx
  src/components/Footer/Address/Address.tsx
  src/components/Footer/Footer/Footer.stories.tsx
  src/components/Footer/Footer/Footer.test.tsx
  src/components/Footer/Footer/Footer.tsx
  src/components/Footer/FooterExtendedNavList/FooterExtendedNavList.test.tsx
  src/components/Footer/FooterExtendedNavList/FooterExtendedNavList.tsx
  src/components/Footer/FooterNav/FooterNav.stories.tsx
  src/components/Footer/FooterNav/FooterNav.test.tsx
  src/components/Footer/FooterNav/FooterNav.tsx
  src/components/Footer/Logo/Logo.stories.tsx
  src/components/Footer/Logo/Logo.test.tsx
  src/components/Footer/Logo/Logo.tsx
  src/components/Footer/SocialLinks/SocialLinks.stories.tsx
  src/components/Footer/SocialLinks/SocialLinks.test.tsx
  src/components/Footer/SocialLinks/SocialLinks.tsx
  src/components/GovBanner/GovBanner.stories.tsx
  src/components/GovBanner/GovBanner.test.tsx
  src/components/GovBanner/GovBanner.tsx
  src/components/Search/Search.stories.tsx
  src/components/Search/Search.tsx
  src/components/forms/DateInput/DateInput.stories.tsx
  src/components/forms/DateInput/DateInput.test.tsx
  src/components/forms/DateInput/DateInput.tsx
  src/components/forms/DateInputGroup/DateInputGroup.test.tsx
  src/components/forms/DateInputGroup/DateInputGroup.tsx
  src/components/forms/Form/Form.tsx
  src/components/forms/RangeInput/RangeInput.stories.tsx
  src/components/forms/RangeInput/RangeInput.test.tsx
  src/components/forms/RangeInput/RangeInput.tsx
  src/components/header/Header/Header.stories.tsx
  src/components/header/MegaMenu/MegaMenu.tsx
  src/components/header/Menu/Menu.tsx
  src/components/header/NavList/NavList.tsx
  src/index.ts
  src/stories/templates/documentation.stories.tsx
  src/stories/templates/landing.stories.tsx
  yarn.lock
Labels: type: release
