Repository trussworks/react-uswds, pull requests merged in 2021-04, with the labels that each got.

#1135 chore(release): 1.15.0
  CHANGELOG.md
  package.json
Labels: type: release

#1045 docs(adr): Increase ReactUSWDS version when updating USWDS version
  docs/adr/0000-template.md
  docs/adr/0001-update-major-version-with-uswds-minor-version.md
Labels: type: documentation

#1140 docs: Update usage in readme, add USWDS version badge
  README.md
Labels: type: documentation

#1106 feat: Update to USWDS 2.10.x
  package.json
  src/components/Footer/Footer/Footer.stories.tsx
  src/components/Footer/Logo/Logo.stories.tsx
  src/components/Footer/Logo/Logo.test.tsx
  src/components/Footer/SocialLinks/SocialLinks.stories.tsx
  src/components/GovBanner/GovBanner.tsx
  src/components/GovBanner/__snapshots__/GovBanner.test.tsx.snap
  src/components/forms/ComboBox/ComboBox.stories.tsx
  src/components/forms/ComboBox/ComboBox.test.tsx
  src/components/forms/ComboBox/ComboBox.tsx
  src/stories/templates/documentation.stories.tsx
  src/stories/templates/landing.stories.tsx
  yarn.lock
Labels: type: dependencies, uswds update

#1099 feat: New Component SiteAlert
  src/components/SiteAlert/SiteAlert.stories.tsx
  src/components/SiteAlert/SiteAlert.test.tsx
  src/components/SiteAlert/SiteAlert.tsx
  src/index.ts
Labels: status: approved

#1101 feat: Radio Button Tile Variant
  src/components/forms/Radio/Radio.stories.tsx
  src/components/forms/Radio/Radio.test.tsx
  src/components/forms/Radio/Radio.tsx
Labels: status: approved

#1104 feat: Checkbox Tile Variant
  src/components/forms/Checkbox/Checkbox.stories.tsx
  src/components/forms/Checkbox/Checkbox.test.tsx
  src/components/forms/Checkbox/Checkbox.tsx
Labels: status: approved

#1162 feat: implement ProcessListHeading subcomponent
  src/components/ProcessList/ProcessList/ProcessList.stories.tsx
  src/components/ProcessList/ProcessList/ProcessList.test.tsx
  src/components/ProcessList/ProcessListHeading/ProcessListHeading.test.tsx
  src/components/ProcessList/ProcessListHeading/ProcessListHeading.tsx
  src/components/ProcessList/ProcessListItem/ProcessListItem.test.tsx
  src/index.ts
  yarn.lock
Labels: status: hold merge
