Repository trussworks/react-uswds, pull requests merged in 2021-09, with the labels that each got.

#1215 feat: SiteAlert child enhancement
  src/components/SiteAlert/SiteAlert.stories.tsx
  src/components/SiteAlert/SiteAlert.test.tsx
  src/components/SiteAlert/SiteAlert.tsx
Labels: status: stale

#1163 refactor: Use React patterns instead of JS API in Tooltip component
  src/components/Tooltip/Tooltip.test.tsx
  src/components/Tooltip/Tooltip.tsx
Labels: type: refactor, status: stale

#1588 chore(release): 2.1.0
  CHANGELOG.md
  package.json
Labels: type: release

#1609 feat: Icon component using SVGR
  .eslintrc
  .storybook/main.ts
  __mocks__/svgrMock.js
  custom.d.ts
  docs/styles_and_assets.md
  example/package.json
  example/src/pages/Icons.tsx
  example/yarn.lock
  jest.config.js
  package.json
  src/components/Icon/Icon.stories.tsx
  src/components/Icon/Icon.test.tsx
  src/components/Icon/Icon.tsx
  src/components/Icon/Icons.stories.tsx
  src/components/Icon/Icons.ts
  src/index.ts
  webpack.config.js
  yarn.lock
Labels: type: feature, high priority
