Repository trussworks/react-uswds, pull requests merged in 2022-01, with the labels that each got.

#1866 chore(release): 2.6.0
  CHANGELOG.md
  package.json
Labels: type: release

#1876 feat: Add focus method to ComboBox ref
  src/components/forms/ComboBox/ComboBox.stories.tsx
  src/components/forms/ComboBox/ComboBox.test.tsx
  src/components/forms/ComboBox/ComboBox.tsx
  src/components/forms/ComboBox/useComboBox.ts
  src/index.ts
Labels: type: feature

#1732 ci: Migrate to Github Actions
  .circleci/config.yml
  .github/workflows/build-and-test.yml
  package.json
Labels: type: development

#1878 fix: Fix Tooltip positioning
  src/components/Tooltip/Tooltip.test.tsx
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/Tooltop.stories.tsx
  src/components/Tooltip/utils.ts
  src/styles/index.scss
Labels: type: bug, high priority

#1879 chore(release): 2.7.0
  CHANGELOG.md
  package.json
Labels: type: release

#1891 chore(release): 2.7.1
  CHANGELOG.md
  package.json
Labels: type: release
