Repository trussworks/react-uswds, pull requests merged in 2022-04, with the labels that each got.

#1947 feat: Deprecate default heading levels
  src/components/Accordion/Accordion.stories.tsx
  src/components/Accordion/Accordion.test.tsx
  src/components/Accordion/Accordion.tsx
  src/components/Alert/Alert.stories.tsx
  src/components/Alert/Alert.test.tsx
  src/components/Alert/Alert.tsx
  src/components/Collection/Collection.stories.tsx
  src/components/Collection/CollectionHeading.test.tsx
  src/components/Collection/CollectionHeading.tsx
  src/components/stepindicator/StepIndicator/StepIndicator.stories.tsx
  src/components/stepindicator/StepIndicator/StepIndicator.test.tsx
  src/components/stepindicator/StepIndicator/StepIndicator.tsx
Labels: type: automerge

#1985 feat(ci): add automerge priority label for Kodiak
  .kodiak.toml
Labels: type: automerge, type: automerge-priority

#1987 ci: change expected date format for DatePicker in Happo
  src/components/forms/DatePicker/DatePicker.stories.tsx
Labels: type: automerge

#2002 chore(tests): Use await on all userEvents
  src/components/forms/ComboBox/ComboBox.test.tsx
Labels: type: automerge

#1999 ci: Happo updates
  .happo.js
  package.json
  src/components/Tooltip/Tooltip.stories.tsx
  yarn.lock
Labels: type: automerge, type: automerge-priority

#1691 feat!: New Component: IconList
  example/src/pages/Icons.tsx
  src/components/Icon/Icon.stories.tsx
  src/components/Icon/Icon.test.tsx
  src/components/Icon/Icons.stories.tsx
  src/components/Icon/Icons.ts
  src/components/IconList/IconList.stories.tsx
  src/components/IconList/IconList.test.tsx
  src/components/IconList/IconList.tsx
  src/components/IconList/IconListContent/IconListContent.test.tsx
  src/components/IconList/IconListContent/IconListContent.tsx
  src/components/IconList/IconListIcon/IconListIcon.test.tsx
  src/components/IconList/IconListIcon/IconListIcon.tsx
  src/components/IconList/IconListItem/IconListItem.test.tsx
  src/components/IconList/IconListItem/IconListItem.tsx
  src/components/IconList/IconListTitle/IconListTitle.test.tsx
  src/components/IconList/IconListTitle/IconListTitle.tsx
  src/components/Modal/ModalCloseButton/ModalCloseButton.tsx
  src/components/forms/InputPrefix/InputPrefix.stories.tsx
  src/components/forms/InputSuffix/InputSuffix.stories.tsx
  src/components/hoc/withDeprecationWarning.test.tsx
  src/components/hoc/withDeprecationWarning.tsx
  src/index.ts
Labels: type: breaking

#2010 ci: Wait for content to load on BigFooterNav before Happo screenshot
  src/components/Footer/FooterNav/FooterNav.stories.tsx
Labels: type: automerge

#1929 feat!: Make Summary Box more flexible
  src/components/SummaryBox/SummaryBox.test.tsx
  src/components/SummaryBox/SummaryBox/SummaryBox.stories.tsx
  src/components/SummaryBox/SummaryBox/SummaryBox.test.tsx
  src/components/SummaryBox/SummaryBox/SummaryBox.tsx
  src/components/SummaryBox/SummaryBoxContent/SummaryBoxContent.test.tsx
  src/components/SummaryBox/SummaryBoxContent/SummaryBoxContent.tsx
  src/components/SummaryBox/SummaryBoxHeading/SummaryBoxHeading.test.tsx
  src/components/SummaryBox/SummaryBoxHeading/SummaryBoxHeading.tsx
  src/index.ts
Labels: type: breaking

#1973 chore: Update contributors across the project
  .all-contributorsrc
  package.json
Labels: type: automerge

#1971 feat: add isInitiallyOpen option to modal
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/Modal.test.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/utils.ts
Labels: type: automerge
